=== warren63/wsdtest1/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="library">
	<xs:complexType>
	    <xs:sequence>
	        <xs:element name="employee" maxOccurs="unbounded">
	        	<xs:complexType>
				    <xs:sequence>
				        <xs:attribute name="ID" type="xs:integer"/>
						<xs:element name="empname" type="xs:string"/>
						<xs:element name="empage" type="xs:integer"/>
				        <xs:element name="empsalary" type="xs:integer" xs:minInclusive value="50000" xs:maxInclusive value="200000"/>
				        <xs:element name="empemailid" type="xs:string"/>
				        <xs:element name="empphonenum" type="xs:integer"/>
						<xs:element name="empdesignation" type="xs:string"/>
				    </xs:sequence>
				</xs:complexType>
	        </xs:element>
	    </xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== warren63/wsdtest1/employee1.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employee.xsd">
  <?xml-stylesheet type="text/xsl" href="employee.xsl"?>
  <employee>
       <empname>Ramesh</empname>
       <empage>25</empage>
       <empsalary>50000</empsalary>
       <empemailid>ramesh@gmail.com</empemailid>
       <empphonenum>5673489960</empphonenum> 
       <empdesignation>Logistic</empdesignation>
  </employee>
  <employee>
       <empname>Shayam</empname>
       <empage>34</empage>
       <empsalary>65000</empsalary>
       <empemailid>shayam@gmail.com</empemailid>
       <empphonenum>5728038364</empphonenum> 
       <empdesignation>Assc.Production</empdesignation>
    </employee>
   <employee>
       <empname>Meghna</empname>
       <empage>40</empage>
       <empsalary>70000</empsalary>
       <empemailid>meghna@gmail.com</empemailid>
       <empphonenum>123456789</empphonenum> 
       <empdesignation>Production</empdesignation>
    </employee>
   <employee>
       <empname>Swati</empname>
       <empage>37</empage>
       <empsalary>90000</empsalary>
       <empemailid>swati@gmail.com</empemailid>
       <empphonenum>987654321</empphonenum> 
       <empdesignation>Ass Manager</empdesignation>
    </employee>
   <employee>
       <empname>Rutan</empname>
       <empage>27</empage>
       <empsalary>100000</empsalary>
       <empemailid>rutan@gmail.com</empemailid>
       <empphonenum>0738264286</empphonenum> 
       <empdesignation>Manager</empdesignation> 
   </employee>  
</library>
